# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Cost_surface_generalization
                                 A QGIS plugin
 Cost surface creation and area delimitation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-28
        copyright            : (C) 2019 by Julien Lacroix
        email                : julien.lacroix@student.uliege.be
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Cost_surface_generalization class from file Cost_surface_generalization.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Cost_surface_generalization import Cost_surface_generalization
    return Cost_surface_generalization(iface)
